### ISSUE TITLE
US-Consistent-DataDictionary Prio: tbd

### ISSUE THREAD

**Issue by mahlmann** [openETCS/product-backlog#18]
As a modeler and validator, I want guaranteed consistency between all instances of data dictionary data.

**Comment by jastram** [comment]
Considering that the Data Dictionary (at least the Eclipse-based one) is neither used, and considering that we lost Lukasz, the developer, I propose to change the status from DEFERRED to ABANDONED (closed).  To discuss this, I will move this issue back to the inbox.

**Comment by mahlmann** [comment]
Closed after discussion in grooming session.
