### ISSUE TITLE
US-Provide-Product-Definition-ADD Prio: 905

### ISSUE THREAD

**Issue by MarcBehrens** [openETCS/product-backlog#36]
As a verifyer (WP4) I need one document summing up the contents of the product to be verified.

**Comment by BaseliyosJacob** [comment]
Part of the ADD Document

**Comment by mahlmann** [comment]
The current state of D3.5.3 is available here: https://github.com/openETCS/modeling/tree/master/openETCS%20ArchitectureAndDesign/D3.5.3
