### ISSUE TITLE
US-Toolchain-CI-Automation Prio: 249

### ISSUE THREAD

**Issue by mahlmann** [openETCS/product-backlog#4]
As a user of the toolchain (WP3 and WP4), I want to be notified when updates are available and install them with a single click.

https://github.com/openETCS/toolchain/labels/US-Auto-Update

**Comment by mahlmann** [comment]
US is set to deferred until Formal Mind will be available in the project again.

**Comment by mahlmann** [comment]
Action on this will be taken again.

**Comment by jastram** [comment]
Closing, as suggested by @mahlmann on 3-Dec-15, as nobody objected.

**Comment by jastram** [comment]
Closing, as suggested by @mahlmann on 3-Dec-15, as nobody objected.
