### ISSUE TITLE
US-SysML-to-Scade Prio: 95

### ISSUE THREAD

**Issue by mahlmann** [openETCS/product-backlog#5]
As a modeler, I need the Papyrus SysML system model to be in sync with the Scade Suite top-level model, so that we have a consistent software design.

**Comment by astante** [comment]
In this branch: https://github.com/openETCS/toolchain/tree/feature-scade-integration under /tool/bundles/org.openetcs.sysml2scade.suite.transformation is the SysML2Scade transformation. The functionality of the plugin is finished (expect for bugs and minor code cleanups). However, as long as the issue with the Scade API is not solved, no integration in the automatic build process is possible. A solution would be to add an external update site for the plugin and the user has to manually agree the terms & conditions of the SCADE API.

**Comment by jastram** [comment]
@mahlmann - this has been closed (fine with me), but it has not been properly documented why it has been closed, ans @astante comment suggests that we could still try to resolve the library integration.  Without the library integration, we cannot make this part of the Eclipse build.

How should be proceed here?  Options are:

1. Just close it
2. Reopen it to resolve the library issue
3. ???

@astante - you are the owner :-) - can you please make the final decision?

**Comment by mahlmann** [comment]
@jastram - I think the reason to close this issue was that plugin itself was considered to be completed ( @astante please correct me if I am wrong ). Feel free to reopen!
