### ISSUE TITLE
US-OBU-Model-Third-Iteration-Perimeter Prio: 930

### ISSUE THREAD

**Issue by mahlmann** [openETCS/product-backlog#53]
As a modeler I want to have a roadmap how the functionality of the reference OBU model will be increased for the third iteration.

**Comment by mahlmann** [comment]
As discussed in the grooming session on February 6th this backlog item is considered to be completed.

@berndhekele
Please add links to the corresponding issues in the WP3 issue tracker to document the progress respectively completion of this backlog item.

**Comment by BerndHekele** [comment]
https://github.com/openETCS/modeling/issues/66
https://github.com/openETCS/modeling/issues/67
https://github.com/openETCS/modeling/issues/68
https://github.com/openETCS/modeling/issues/69
