### ISSUE TITLE
US-OBU-Model-Roadmap Prio: 1000

### ISSUE THREAD

**Issue by mahlmann** [openETCS/product-backlog#54]
As a modeler I want to have a scope of functionality of the OBU model for the final project goal, i.e. an OBU able to run on the Amsterdam Utrecht line.

**Comment by faustco** [comment]
Text should read
As a modeler I want to have a scope of functionality of the OBU model for the next iteration.

**Comment by BaseliyosJacob** [comment]
This is defined in the US Stories which contain the functional requirements specification.
