### ISSUE TITLE
US-Operational-Scenarios-on-Utrecht-Amsterdam Prio: 900

### ISSUE THREAD

**Issue by BaseliyosJacob** [openETCS/product-backlog#61]
As an operator (WP1) I want the model of the third iteration to be verified and validated against the following use cases

https://github.com/openETCS/modeling/labels/US-Operational%20Scenarios%20on%20Utrecht%20Amsterdam

**Comment by BaseliyosJacob** [comment]
User stories should be considered by WP 4

**Comment by MarcBehrens** [comment]
relates to #62

**Comment by mahlmann** [comment]
duplicate of #61 . closed.
