### ISSUE TITLE
US-WP 3-Description of Work Prio:

### ISSUE THREAD

**Issue by BaseliyosJacob** [openETCS/product-backlog#63]

**Comment by BaseliyosJacob** [comment]
As a WP 1 i need a description of work for WP 3. The description of work should contain the methods, process, tooldecision, roadmap, scope, ... and will be done by the WP 3 leader.

**Comment by mahlmann** [comment]
The existing documents in https://github.com/openETCS/modeling/tree/master/DescriptionOfWork
have to be checked.

**Comment by mahlmann** [comment]
Not considered relevant for the moment, issue will be closed.
