### ISSUE TITLE
US-V&V backlog as counter part of WP 3 User Story backlog Prio: 950

### ISSUE THREAD

**Issue by BaseliyosJacob** [openETCS/product-backlog#70]
As a modeller i would like to see a V&V backlog for the counter part of the WP 3 User Story backlog.

**Comment by MarcBehrens** [comment]
a first set was groomed, see [validation repository](https://github.com/openETCS/validation/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+Verification+User+Story)

the missing set is planned to be groomed next week
