### ISSUE TITLE
US-Scade-to-Open Prio: 600

### ISSUE THREAD

**Issue by jastram** [openETCS/product-backlog#76]
As a user, I want to convert the Scade Suite artefacts into an open format, so that I can consume them outside Scade

**Comment by dalzilio** [comment]
redundant issue, it can be closed or merged with these other issues

answer is covered by issues 500 and 505:
https://github.com/openETCS/toolchain/issues/500
https://github.com/openETCS/toolchain/issues/505

**Comment by jastram** [comment]
Closing, as suggested by @mahlmann on 3-Dec-15, as nobody objected.
